# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main
- dev

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)'
    gradleWrapperFile: '$(Build.Repository.LocalPath)/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: JDKVersion
    jdkVersionOption: '1.17'
    tasks: 'clean build test assembleRelease assembleDebug assembleAndroidTest'
